name: Deployment pipeline
# ***** You can use "act" to run the workflow locally: https://github.com/nektos/act
on:
  push:
    branches:
      - master
  # PR trigger
  pull_request:
    branches: [master]
    types: [opened, synchronize]

# env variables: https://docs.github.com/en/actions/learn-github-actions/variables
env:
  COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
  skipDeploymentAndTagging: ${{ contains(join(toJson(github.event.commits.*.message)), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      # The name of a step is optional
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: E2E tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:3001
      # info: https://fullstackopen.com/en/part11/deployment
      # info: https://github.com/AkhileshNS/heroku-deploy
      - name: Print commit messages
        run: echo "$COMMIT_MESSAGES"
          echo "$skipDeploymentAndTagging"
      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' && !"$skipDeploymentAndTagging" }}
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: pokedex-1234
          heroku_email: hinnawiabdullah@gmail.com
          # info: https://github.com/marketplace/actions/deploy-to-heroku
          healthcheck: 'https://pokedex-1234-67d4b42eed78.herokuapp.com/health'
          checkstring: 'ok'
          # Make the action wait for 5 sec before performing the health check
          delay: 5
          # Rollback on healthcheck failure
          rollbackonhealthcheckfailed: true
  tag_release:
    if: ${{ github.event_name == 'push' && !"$skipDeploymentAndTagging" }}
    # Jobs are executed in parallel, so make sure that tag_release waits simple_deployment_pipeline to to be executed first
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump (increase) version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          # the third-party action needs the token for authentication in the repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch # semantic versioning: 1.2.3 => {major}.{minor}.{patch}
          DRY_RUN: true
