name: Deployment pipeline
# ***** You can use "act" to run the workflow locally: https://github.com/nektos/act
on:
  push:
    branches:
      - master
  # PR trigger
  pull_request:
    branches: [master]
    types: [opened, synchronize] # this means, that the workflow will run when a PR into the master branch is opened or updated.

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      # The name of a step is optional
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: E2E tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:3001
      # info: https://fullstackopen.com/en/part11/deployment
      # info: https://github.com/AkhileshNS/heroku-deploy
      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: pokedex-1234
          heroku_email: hinnawiabdullah@gmail.com
          # info: https://github.com/marketplace/actions/deploy-to-heroku
          healthcheck: 'https://pokedex-1234-67d4b42eed78.herokuapp.com/health'
          checkstring: 'ok'
          # Make the action wait for 5 sec before performing the health check
          delay: 5
          # Rollback on healthcheck failure
          rollbackonhealthcheckfailed: true
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    # Jobs are executed in parallel, so make sure that tag_release waits simple_deployment_pipeline to to be executed first
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump (increase) version and push tag
        # When using a third party action such that github-tag-action it might be a good idea to specify the used version with hash instead of using a version number. The reason for this is that the version number, that is implemented with a Git tag can in principle be moved. So today's version 1.67.0 might be a different code that is at the next week the version 1.67.0!
        # However, the code in commit with a particular hash does not change in any circumstances, so if we want to be 100% sure about the code we use, it is safest to use the hash.
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36 # corresponds to the version 1.67.0
        env:
          # the third-party action needs the token for authentication in the repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch # semantic versioning: 1.2.3 => {major}.{minor}.{patch}
          DRY_RUN: false # true will make the action output the next version number without creating or tagging the release.
